version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/testing.malady.co/
hooks:
  ApplicationStop: 
    - location: scripts/stop_application
      timeout: 400
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 400
  ApplicationStart:
    - location: scripts/start_application
      timeout: 400    